// Offline cryptographic license system (Ed25519 signed keys).
// No server required. Keys generated by generate-license.js CLI tool.
//
// Key format: CLAW-{base64url(payload_json + 64-byte Ed25519 signature)}
// Machine binding: HMAC seal on local license.json (prevents file copy)
// Offline: works forever until expiry date in signed payload.
// Revocation: optional online check against revoked-keys.json gist.

const os = require('os');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const https = require('https');

const PUBLIC_KEY_PEM = fs.readFileSync(
  path.join(__dirname, 'license-public.pem'), 'utf-8'
);
const PUBLIC_KEY = crypto.createPublicKey(PUBLIC_KEY_PEM);

const REVOKED_URL = 'https://gist.githubusercontent.com/huybt-peter/raw/revoked-keys.json';

// ---- seal key (obfuscated fragments, concat at runtime) ----
const _s1 = 'mdc-seal';
const _s2 = '-v2-';
const _s3 = '2026q2';
function _sealSecret(machineId) {
  return crypto.createHash('sha256').update(_s1 + _s2 + _s3 + machineId).digest('hex');
}

// ---- machine fingerprint ----

function _computeMachineIdRaw() {
  const hostname = os.hostname();
  const ifaces = os.networkInterfaces();
  const names = Object.keys(ifaces).sort();
  const virtualPatterns = /^(veth|docker|virbr|br-|vmware|virtualbox|vethernet)/i;
  let mac = null;
  for (const name of names) {
    if (virtualPatterns.test(name)) continue;
    for (const info of ifaces[name]) {
      if (!info.internal && info.mac && info.mac !== '00:00:00:00:00:00') {
        mac = info.mac;
        break;
      }
    }
    if (mac) break;
  }
  if (!mac) mac = 'no-mac';
  const raw = hostname + '|' + mac + '|' + os.platform();
  return crypto.createHash('sha256').update(raw).digest('hex').slice(0, 32);
}

let _cachedMachineId = null;

function getMachineId() {
  if (_cachedMachineId) return _cachedMachineId;
  const appData = process.env.APPDATA || (process.platform === 'darwin'
    ? path.join(os.homedir(), 'Library', 'Application Support')
    : path.join(os.homedir(), '.config'));
  const midFile = path.join(appData, '9bizclaw', '.machine-id');
  try {
    const stored = fs.readFileSync(midFile, 'utf-8').trim();
    if (stored && stored.length === 32) { _cachedMachineId = stored; return stored; }
  } catch {}
  const mid = _computeMachineIdRaw();
  try { fs.mkdirSync(path.dirname(midFile), { recursive: true }); fs.writeFileSync(midFile, mid, 'utf-8'); } catch {}
  _cachedMachineId = mid;
  return mid;
}

// ---- HMAC seal ----

function computeSeal(data) {
  const mid = data.machineId || getMachineId();
  const payload = (data.key || '') + mid + (data.activatedAt || '') + (data.email || '');
  return crypto.createHmac('sha256', _sealSecret(mid)).update(payload).digest('hex');
}

function verifySeal(data) {
  if (!data || !data.seal) return false;
  const expected = computeSeal(data);
  const a = Buffer.from(data.seal || '', 'hex');
  const b = Buffer.from(expected, 'hex');
  if (a.length !== b.length) return false;
  return crypto.timingSafeEqual(a, b);
}

// ---- workspace integration ----

let _getWorkspace = null;

function init(getWorkspaceFn) {
  _getWorkspace = getWorkspaceFn;
}

function licensePath() {
  const ws = _getWorkspace ? _getWorkspace() : null;
  if (!ws) return null;
  return path.join(ws, 'license.json');
}

function readLicense() {
  const p = licensePath();
  if (!p) return null;
  try {
    return JSON.parse(fs.readFileSync(p, 'utf-8'));
  } catch { return null; }
}

function writeLicense(data) {
  const p = licensePath();
  if (!p) return false;
  try {
    data.seal = computeSeal(data);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, JSON.stringify(data, null, 2), 'utf-8');
    return true;
  } catch { return false; }
}

// ---- Ed25519 signature verification ----

function base64urlDecode(str) {
  let s = str.replace(/-/g, '+').replace(/_/g, '/');
  while (s.length % 4) s += '=';
  return Buffer.from(s, 'base64');
}

function verifyLicenseKey(keyStr) {
  try {
    let raw = keyStr.trim();
    if (raw.startsWith('CLAW-')) raw = raw.slice(5);
    raw = raw.replace(/[\s\r\n]/g, '');

    const decoded = base64urlDecode(raw);
    if (decoded.length < 65) return { valid: false, error: 'invalid_key' };

    const sigBytes = decoded.slice(decoded.length - 64);
    const payloadBytes = decoded.slice(0, decoded.length - 64);

    const isValid = crypto.verify(null, payloadBytes, PUBLIC_KEY, sigBytes);
    if (!isValid) return { valid: false, error: 'invalid_key' };

    const payload = JSON.parse(payloadBytes.toString('utf-8'));

    if (payload.v) {
      const expiry = new Date(payload.v).getTime();
      if (Date.now() > expiry) return { valid: false, error: 'expired', payload };
    }

    return { valid: true, payload };
  } catch (e) {
    return { valid: false, error: 'invalid_key' };
  }
}

// ---- status check ----

function checkLicenseStatus() {
  const data = readLicense();
  if (!data) return { status: 'no_license' };
  if (!verifySeal(data)) return { status: 'invalid', reason: 'seal_broken' };
  if (!data.key) return { status: 'no_license' };

  const verify = verifyLicenseKey(data.key);
  if (!verify.valid) {
    if (verify.error === 'expired') {
      return { status: 'expired', key: maskKey(data.key), email: data.email };
    }
    return { status: 'invalid', reason: 'signature_invalid' };
  }

  const payload = verify.payload;
  let daysLeft = null;
  if (payload.v) {
    daysLeft = Math.floor((new Date(payload.v).getTime() - Date.now()) / 86400000);
  }

  return {
    status: 'valid',
    key: maskKey(data.key),
    email: data.email || payload.e,
    plan: payload.p || 'premium',
    daysLeft,
    validUntil: payload.v,
  };
}

// ---- key formatting helpers ----

function maskKey(key) {
  if (!key || key.length < 15) return 'CLAW-****';
  return key.slice(0, 12) + '...' + key.slice(-4);
}

// ---- activation (offline) ----

async function activateLicense(key) {
  const verify = verifyLicenseKey(key);
  if (!verify.valid) return { success: false, error: verify.error };

  const payload = verify.payload;
  const machineId = getMachineId();

  const data = {
    key,
    email: payload.e || '',
    machineId,
    activatedAt: new Date().toISOString(),
    plan: payload.p || 'premium',
    validUntil: payload.v || null,
  };
  const wrote = writeLicense(data);
  if (!wrote) return { success: false, error: 'write_failed' };

  // Best-effort revocation check (non-blocking)
  checkRevoked(key).catch(() => {});

  return { success: true };
}

// ---- revocation check (optional, best-effort) ----

let _revokedCache = null;
let _revokedCacheTime = 0;

async function checkRevoked(key) {
  const now = Date.now();
  if (_revokedCache && (now - _revokedCacheTime) < 86400000) {
    return _isKeyRevoked(key, _revokedCache);
  }

  return new Promise((resolve) => {
    const req = https.get(REVOKED_URL, { timeout: 8000 }, (res) => {
      if (res.statusCode !== 200) return resolve(false);
      let buf = '';
      res.on('data', c => { buf += c; if (buf.length > 100000) req.destroy(); });
      res.on('end', () => {
        try {
          _revokedCache = JSON.parse(buf);
          _revokedCacheTime = now;
          if (_isKeyRevoked(key, _revokedCache)) {
            const p = licensePath();
            if (p) try { fs.unlinkSync(p); } catch {}
            resolve(true);
          } else {
            resolve(false);
          }
        } catch { resolve(false); }
      });
    });
    req.on('error', () => resolve(false));
    req.on('timeout', () => { req.destroy(); resolve(false); });
  });
}

function _isKeyRevoked(key, list) {
  if (!Array.isArray(list)) return false;
  const hash = crypto.createHash('sha256').update(key).digest('hex').slice(0, 16);
  return list.some(h => h === hash);
}

// ---- revalidation (local signature check + optional revocation) ----

async function revalidateLicense() {
  const data = readLicense();
  if (!data || !data.key) return false;

  const verify = verifyLicenseKey(data.key);
  if (!verify.valid) return false;

  try {
    const revoked = await checkRevoked(data.key);
    if (revoked) return false;
  } catch {}

  return true;
}

// ---- clear ----

async function clearLicense() {
  const p = licensePath();
  if (p) try { fs.unlinkSync(p); } catch {}
}

module.exports = {
  init, getMachineId, checkLicenseStatus, activateLicense,
  revalidateLicense, clearLicense, maskKey, verifyLicenseKey,
};
